version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package
      - run: mvn test -DsuiteXmlFile=testng.xml

workflows:
  version: 2
  build:
    jobs:
      - build-and-test

